### ISSUE TITLE
Change issues labels

### ISSUE THREAD

**Issue by miguelbassila** [elo7/oahu#10]
And if we used another way to label our issues?

https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
e.g.: https://github.com/Alamofire/Alamofire/labels

**Comment by aterribili** [comment]
nice :)

**Comment by aterribili** [comment]
@miguelbassila did you change the issue/labels?

**Comment by miguelbassila** [comment]
no.. they stills the same! :cry:

**Comment by aterribili** [comment]
Oh man, we always need your help :heart:

**Comment by miguelbassila** [comment]
:heart:

**Comment by miguelbassila** [comment]
if you want, i can switch de labels.

**Comment by aterribili** [comment]
Do it, if you can :)
